* I was trying to figure out some application/games for kids based on Linux to teach my Kid about some programming, I tried to teach him some computer at times and found him very interested in leaning stuff. There must be many for windows but being myself an avid Linux user from quite a long time, I really want to introduce him to Linux quite early, unlike me, who got my hands on Linux late in life and still waiting to explore the endless possiblities it offers.

There is always these question, Why computers? and Why to kids? Are they are smart enough to handle computers. 
We have very common non-sensical answers or myths around which may suggest the Computers are only for grown ups and kids might not be able to handle the strain it may cause to their eyes, yes in this case I do agree, and hence we need to understand to limit their onscreen time; but doing this also we can ensure to learn our kids about computers.

Here is a list of few application which I was able to collate using the net and ofcoure google.com :)

*** [[http://gcompris.net/index-en.html][Gcompris]] :
Gcompris is a suite of around 100 games with different difficulty levels suited for kids between age 2-10, The activities are divided up between sections such as Math, Reading, Amusement. The entire suite is available on most of the distributions standard repostiries. Gcompris is a free software, which means I can adapt it, change it, improve it and most importantly can share this among thousands of other childrens who might want to use it. Below are some of the things Gcompris is offering.

- Computer discovery: keyboard, mouse, different mouse gestures, ...
- arithmetic: table memory, enumeration, double entry table, mirror image, ...
- science: the canal lock, the water cycle, the submarine, electric simulation ...
- geography: place the country on the map
- games: chess, memory, connect 4, oware, sudoku ...
- reading: reading practice
- other: learn to tell time, puzzle of famous paintings, vector drawing, cartoon making, ...  

More information on this project can be found at [[http://gcompris.net/index-en.html][Gcompris Website]]. And [[http://en.wikipedia.org/wiki/GCompris][Gcompris Wikipedia]] does has a simple overview of this project too.

On debian or debian alike systems, use
#+begin_src sh
sudo apt-get install gcompris
#+end_src

*** [[http://tux4kids.alioth.debian.org/][Tux4Kids]]
Tux4Kids develops high-quality software for kids, with the goal of combining fun and learning into an irresistable package. Our software is free: you can download it for use at home or onto hundreds of computers in a school. We support all major platforms, including Windows, Macintosh, and Linux/Unix. Our programs are used by people around the globe, and they have been translated into dozens of different languages. As open-source software, these programs can be freely extended or customized, and they are supported by active communities of volunteer developers.
Whether you're a parent, a teacher, or a kid, give Tux4Kids software a try!

**** Tuxtype
Tuxtype is an educational typing tutor for kids starting tux. 

#+begin_src sh
sudo apt-get install tuxtype
#+end_src

for other installation instrcutions can be found at http://tux4kids.alioth.debian.org/tuxtype/download.php.

**** Tuxpaint
There is a little painintg program to make your kid learn paint. This lets kids draw things and is good for them to learn moving the mouse and do other stuff. his remarkable drawing program empowers kids to be creative in an environment complete with magic tools and sound effects.

#+begin_src sh
sudo apt-get install tuxpaint
#+end_src

for other installation instrcutions can be found at http://www.tuxpaint.org/download/.

**** TuxMath
Lets kids hone their arithmetic skills while they defend penguins from incoming comets, or offers them a chance to explore the asteroid belt with only their factoring abilities to bring them through safely  

#+begin_src sh
sudo apt-get install tuxmath
#+end_src

for other installation instrcutions can be found at http://tux4kids.alioth.debian.org/tuxmath/download.php

I think for the beginning I will just go ahead and start with this.  May be when I have to teach him further about programming, I have my list complete with Scratch, Alice and Shoes which may help me if required in the next coming years.

BTW, forgot to mention there are real good linux distributions just aimed for kids, and may help kids learn a lot of things on their own while managing their own personal latops. The above utilities are good if you have only one machine and you want your kid to allow to use these too.

There are also articles for making to learn kids to program at [[http://archive09.linux.com/feature/155203][linux.com]]. Some of them mentioned are scratch, Alice and Shoes.
